name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: eregon/use-ruby-action@v1
      with:
        ruby-version: 2.6
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Run a multi-line script
      run: |
        ruby -v
        node -v
        npm i
        bundle --path=.bundle/gems
        bundle exec rake build
        find .

    - name: Deploy
      if: success()
      uses: crazy-max/ghaction-github-pages@v1
      with:
        target_branch: gh-pages
        build_dir: public/blog/test/
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}